Parameters:
  PersonalGitHubToken:
    Type: String
    Description: Provide your personal GitHub access token for CodeBuild to access your GitHub repo
    MinLength: 10
    ConstraintDescription: Personal GitHub token is required

Resources:
  PortoflioWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jakub-grzelak-cf-website
      WebsiteConfiguration:
        IndexDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PortoflioWebsiteBucket
      PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: GetObjectForPublic
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::' 
                  - !Ref PortoflioWebsiteBucket
                  - /*
    
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      ServerType: GITHUB
      Token: !Ref PersonalGitHubToken
      AuthType: PERSONAL_ACCESS_TOKEN
    
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: jakub-grzelak-portfolio-website
      Description: CodeBuild project for my portfolio website
      Source:
        Type: GITHUB
        Location: https://github.com/Reivah/CloudFormation-Portfolio-Website.git
        GitCloneDepth: 1
        Auth:
          Resource: !Ref CodeBuildSourceCredential
          Type: OAUTH
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/main
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:7.0
        ComputeType: BUILD_GENERAL1_SMALL
      Artifacts:
        Type: S3
        Location: !Sub arn:aws:s3:::${PortoflioWebsiteBucket}
        Name: '/'
        EncryptionDisabled: true
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: jakub-grzelak-website-portfolio-CloudWatchLogs
  
  CloudWatchLogsRetention:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: jakub-grzelak-website-portfolio-CloudWatchLogs
      RetentionInDays: 14
  
  CodeBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuild-role-access-for-website-portfolio
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: policy-for-codebuild-website-portfolio
          PolicyDocument: 
            Version: 2012-1017
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
    
      Path: /
        
Outputs:
  OutputWebsiteURL:
    Description: Navigate to website URL
    Value: !GetAtt
      - PortoflioWebsiteBucket
      - WebsiteURL
    
        